### ISSUE TITLE
videojs :: missing code for aes/token scenario. 

### ISSUE THREAD

**Issue by phwecker** [Azure-Samples/media-services-3rdparty-player-samples#18]
index.js of videojs seems to be missing a code section that is actually referenced in our own "how to use videojs with AMS" example ... 

    if (options.uri.includes("keydeliver")) {
      options.headers = options.headers || {};
      options.headers.Authorization = "Bearer=" + this.getInputToken();
    }

the index.js does some checks in setupTokenForDecrypt() to determine when to enter 

    if (authentication) {
      options.headers = options.headers || {};
      options.headers.Authorization = "Bearer=" + this.getInputToken();
      console.log("AUTH :: ", options.headers.Authorization);
    }

but it seems in a scenario where only TOKEN is selected in the form and a TOKEN is provided "authenteication" is not set to true and hence the baerer token is never applied -> AES encrypted streams do not play. 

after adding the mentioned section to the code it works fine.

**Comment by johndeu** [comment]
Merged. Closing issue
